"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {'emulate_shell_environment':True, 'packages':'generate_iconset', 'iconfile':'new.icns'}

setup(
    app=APP,
    name="PNG2ICNS",
    version=1.5,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

